server:
  port: ${RAPIDUS_SERVER_PORT}
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${RAPIDUS_MARIADB_URL}
    username: ${RAPIDUS_MARIADB_USER_NAME}
    password: ${RAPIDUS_MARIADB_USER_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    show_sql: true

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    s3:
      bucket: ${AWS_BUCKET_NAME}
      url: ${AWS_URL}
    stack:
      auto: false